/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@any-design/anyui')['Button']
    AClickableText: typeof import('@any-design/anyui')['ClickableText']
    AContent: typeof import('@any-design/anyui')['Content']
    AFloat: typeof import('@any-design/anyui')['Float']
    AFormItem: typeof import('@any-design/anyui')['FormItem']
    AInput: typeof import('@any-design/anyui')['Input']
    ALayout: typeof import('@any-design/anyui')['Layout']
    ApiKeyListPanel: typeof import('./src/components/user/panels/ApiKeyListPanel.vue')['default']
    BottomFooter: typeof import('./src/components/BottomFooter.vue')['default']
    'IMaterialSymbols:arrowUpwardRounded': typeof import('~icons/material-symbols/arrow-upward-rounded')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    Landing: typeof import('./src/components/Landing.vue')['default']
    LoginForm: typeof import('./src/components/user/forms/LoginForm.vue')['default']
    Passport: typeof import('./src/components/user/Passport.vue')['default']
    RegisterForm: typeof import('./src/components/user/forms/RegisterForm.vue')['default']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
    UserCenter: typeof import('./src/components/user/UserCenter.vue')['default']
  }
}
